import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { NavigationMenuDemo } from "./Module/NavigationMenu";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex flex-col min-h-screen overflow-y-auto">
        <nav className="bg-white/60 backdrop-blur-xl w-full sticky top-0 z-50 py-2">
          <NavigationMenuDemo />
        </nav>
        <main className="flex-grow mt-12">
          <div className="mx-auto p-4 flex justify-center">{children}</div>
        </main>
      </body>
    </html>
  );
}
